### ISSUE TITLE
yarn dev – error

### ISSUE THREAD

**Issue by nepofigist** [TryGhost/Alto#27]
Good day,

Sorry for stupid question, I'm just a newbie trying to install and update theme. When I try to use "yarn dev" command I see the following error:

`yarn run v1.22.4
warning ../../../package.json: No license field
warning alto@1.0.0: The engine "ghost" appears to be invalid.
warning alto@1.0.0: The engine "ghost-api" appears to be invalid.
$ gulp
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /var/www/ghost/content/themes/Alto-master/node_modules/beeper/index.js
require() of ES modules is not supported.
require() of /var/www/ghost/content/themes/Alto-master/node_modules/beeper/index.js from /var/www/ghost/content/themes/Alto-master/gulpfile.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /var/www/ghost/content/themes/Alto-master/node_modules/beeper/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/var/www/ghost/content/themes/Alto-master/gulpfile.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.
`

**Comment by minimaluminium** [comment]
Hey @nepofigist, that was related with updated version (v3) of `beeper` that is used in the development workflow. We just reverted the package version in https://github.com/TryGhost/Alto/commit/dd1c046146e2ad2b74e4fc62014d01132d37f520. You'll now be able to run `yarn dev`.

Thanks for the report :)
